First iteration
rbobillo/OnDiraitDeLaMagie pull request #3
Opened 2019-07-27 16:01 UTC by artemys

First_iteration done : 
- age 
- jail
- die
- obliviate
 age / obliviate don't working on swagger.
Need a check on return header.

2019-07-27 16:15 UTC, rbobillo commented on first_iteration/magic/api/api_test.go
> +package api
Pour l'instant, on peut s'en battre les couilles,
mais faudra faire des tests unitaires un peu partout dans le code, ainsi que des tests d'intégration :)

2019-07-28 01:15 UTC, rbobillot requested changes
En theorie je n'ai rien oublie :)
Pour l'instant j'ai fait une review uniquement basee sur le code (syntaxe, comportement theorique...)
Dans l'ensemble c'est tres bien !

Y a 2 ou 3 petouilles qui se balladent par-ci par-la, mais rien de grave.
Certains commentaires peuvent sembler un peu secs (mais c'est juste que je ne voulais pas raconter ma vie haha)

Lis les bien tous, et effectue les changements necessaires.
Pour ce faire, commence par lire une fois tous les commentaires:
- ca te donnera une vision globale du chantier
- certains commentaires sont des doublons, je n'ai pas fait la review dans un ordre chronologique, semantique ou alphabetique

Un dernier commentaire de fdp, il manque 2 choses importantes:
- `go fmt` (tu peux le faire depuis Goland: `Tools > Go Tools > Go Fmt Project`)
- `golint` (ne t'embete pas a setup ca en tant que tool, run le direct dans ton terminal: ```for i in `find . -type f -iname '*.go'`; do golint $i ; done```)
Parce que la, tout s'est un peu illumine comme Las Vegas :D 

Une fois que tu aura tout corrige,
on fera une 2e review,
sur le fonctionnement de l'app cette fois ;)

2019-07-28 01:15 UTC, rbobillot commented on first_iteration/magic/magicinventory/magicinventory.go
> +//func getId(r *http.Request) string{
Attention a ne pas laisser du code mort (genre des commentaires sans inutilisables)

2019-07-28 01:15 UTC, rbobillot commented on first_iteration/magic/api/swaggerui/swagger.yaml
> +        200:
cf doc: code 204, cette route ne renvoie pas de data

2019-07-28 01:15 UTC, rbobillot commented on first_iteration/magic/api/swaggerui/swagger.yaml
> +        200:
cf doc: code 201 (remaniement)

2019-07-28 01:15 UTC, rbobillot commented on first_iteration/magic/api/swaggerui/swagger.yaml
> +        200:
cf doc: code 204, cette route ne renvoie pas de data

2019-07-28 01:15 UTC, rbobillot commented on first_iteration/magic/api/swaggerui/swagger.yaml
> +          description: "Cannot update the database (might not existe)"
"might not existe" :D

2019-07-28 01:15 UTC, rbobillot commented on first_iteration/magic/api/swaggerui/swagger.yaml
> +            $ref: '#/definitions/SingleWizardResponse'
Peut-etre faudrait-il renvoyer un autre objet:
 -> par defaut, SingleWizardResponse a son champ "dead" a false
 -> il serait judicieux de renvoyer un wizard avec un champ "dead" a true par defaut :)

2019-07-28 01:15 UTC, rbobillot commented on first_iteration/magic/api/swaggerui/swagger.yaml
> +            $ref: '#/definitions/SingleWizardResponse'
Peut-etre faudrait-il renvoyer un autre objet:
 -> par defaut, SingleWizardResponse a son champ "arrested" a false
 -> il serait judicieux de renvoyer un wizard avec un champ "arrested" a true par defaut :)

2019-07-28 01:15 UTC, rbobillot commented on first_iteration/magic/magicinventory/magicinventory.go
> +
attention aux lignes vides

2019-07-28 01:15 UTC, rbobillot commented on first_iteration/magic/magicinventory/magicinventory.go
> +func UpdateWizardByID(w *http.ResponseWriter, db *sql.DB, query string, args  interface{}) (err error){
Attention au naming 'UpdateWizardByID'. Tu as 2 choix:
- UpdateWizard
- UpdateWizardsByID (etant donne que j'etais parti sur un GetWizardsByID, autant partir la-dessus)

2019-07-28 01:15 UTC, rbobillot commented on first_iteration/magic/magicinventory/magicinventory.go
> +// CheckWizardStatusById check if the status of an wizard is already set {jail, die, whatever)
Attention au code mort

2019-07-28 01:15 UTC, rbobillot commented on first_iteration/magic/magicinventory/magicinventory.go
> +		(*w).WriteHeader(http.StatusNotFound)
Pas de gestion retour HTTP (header, body...) ici.

Ici, on ne s'occupe que des interactions avec la DB.

C'est dans la partie api que tu geres ca.
Il faut donc mettre a jour de retour de cette fonction :)

2019-07-28 01:15 UTC, rbobillot commented on first_iteration/magic/api/wizards.go
> +	row := db.QueryRow("SELECT * FROM wizards WHERE id = $1", id)
Peut-etre va-t-il falloir extraire les interactions avec la DB, dans magicinventory.go ;)
(meme remarque pour GetWizards)

2019-07-28 01:15 UTC, rbobillot commented on first_iteration/magic/magicinventory/magicinventory.go
> +func DeleteWizardByID(db *sql.DB, args interface{}) (err error) {
- naming: DeleteWizardsByID
- args: on sait qu'on n'a qu'un argument (id), et qu'une seule action (delete), donc autant prendre un parametre `id string`

2019-07-28 01:15 UTC, rbobillot commented on first_iteration/magic/api/spawn.go
> +
code de retour 201 a ecrire dans le header
cf doc, et mes commentaires du swagger.yaml

2019-07-28 01:15 UTC, rbobillot commented on first_iteration/magic/api/obliviate.go
> +// Nimporte quoi
Attention, mauvais commentaire.
Et la fonction publique n'est pas documentee !

2019-07-28 01:15 UTC, rbobillot commented on first_iteration/magic/api/obliviate.go
> +	if err != nil {
`err` n'est assigne qu'une seule fois
Autant l'instancier dans le code (pas dans la declaration de la fonction), et retourner nil tout a la fin, et ne retourner `err` que dans la condition d'echec

2019-07-28 01:15 UTC, rbobillot commented on first_iteration/magic/api/obliviate.go
> +	return err
il manque le header de succes (cf doc et commentaires swagger) ;)

2019-07-28 01:15 UTC, rbobillot commented on first_iteration/magic/api/jail.go
> +	if err == sql.ErrNoRows {
Il y a un doublon de gestion d'erreur
Mieux vaut gerer l'erreur `sql.ErrNoRows` dans magicinventory.go (separation of concerns), et renvoyer une erreur qui sera geree une seule fois ici

2019-07-28 01:15 UTC, rbobillot commented on first_iteration/magic/api/jail.go
> +
Il manque le body de retour :)

2019-07-28 01:15 UTC, rbobillot commented on first_iteration/magic/api/jail.go
> +func UpdateWizardsJail(w *http.ResponseWriter, r *http.Request, db *sql.DB) (err error){
Attention au naming: `JailWizard` ou `ArrestWizard`, voire `JailWizardsByID`
Car ici, le nom n'a pas vraiment de sens, d'un point de vue metier

2019-07-28 01:15 UTC, rbobillot commented on first_iteration/magic/api/die.go
> +func UpdateWizardsDeath(w *http.ResponseWriter, r *http.Request, db *sql.DB) (err error){
Attention au naming: KillWizard ou KillWizardsByID
Car ici, le nom n'a pas vraiment de sens, d'un point de vue metier

2019-07-28 01:15 UTC, rbobillot commented on first_iteration/magic/api/die.go
> +// Todo: UpdateWizardDeath and UpdateWizardJail are almost the same function
Je pense que tu peux retirer le `TODO` :)
Et attention a la ligne vide en dessous

Par precaution, pense toujours a utiliser l'onglet TODO, en bas a gauche de Goland (non loin de l'onglet terminal), ca te permet de voir les `TODO` qu'il te reste.
Par convention, mieux vaut qu'il n'y ait plus de `TODO` dans une PR qui les concerne (surtout s'ils n'ont plus lieu d'etre) :)

2019-07-28 01:15 UTC, rbobillot commented on first_iteration/magic/api/die.go
> +	log.Printf("/wizards/{%s}/die", id)
Pas besoin de garder les `{}` dans le print :) (j'ai vu ca a 2 ou 3 endroits)

2019-07-28 01:15 UTC, rbobillo commented on first_iteration/magic/api/age.go
> +// UpdateWizardsAges function request the Magic Inventory
Le attention au naming du commentaire, qui ne correspond pas au nom de la fonction publique :)

2019-07-28 01:15 UTC, rbobillo commented on first_iteration/magic/api/age.go
> +func UpdateWizardsAge(w *http.ResponseWriter, r *http.Request, db *sql.DB) (err error){
Le naming n'a pas de sens d'un point de vue metier (dans la vie, on vieillit, on ne met pas son age a jour)
`AgeWizards` serait plus exact :)

2019-07-28 16:21 UTC, artemys commented on first_iteration/magic/api/age.go
> +func UpdateWizardsAge(w *http.ResponseWriter, r *http.Request, db *sql.DB) (err error){
Donc j'oublie la notion d'update ?

2019-07-28 16:30 UTC, artemys commented on first_iteration/magic/api/jail.go
> +	if err == sql.ErrNoRows {
Le probleme que j'ai rencontrer c'est que le message es specifique a jail (already in jail) et die (already dead) je ne pouvais pas le mettre dans UpdateWizardByID car c'est une fonction generique.

2019-07-28 19:17 UTC, rbobillo commented on first_iteration/magic/api/jail.go
> +	if err == sql.ErrNoRows {
Le message est specifique,
mais moi je parle de **l'erreur** (pas du message).

`sql.ErrNoRows` est propre a de la logique SQL, et non a de la logique metier.
On peut donc la gerer dans magicinventory.go, et mettre un log du genre "cannot update wizard with id {id}: wizard not found", puis renvoyer une erreur
-> ainsi, la jail.go n'a plus qu'a gerer le `if err != nil` et mettre a jour le header+body de reponse, et pourquoi pas faire un joli log comme le tien

2019-07-29 21:25 UTC, rbobillot requested changes
Il ne reste plus grand chose a corriger, c'est cool

2019-07-29 21:25 UTC, rbobillo commented on first_iteration/magic/api/jail.go
> +func JailWizardByID(w *http.ResponseWriter, r *http.Request, db *sql.DB) (err error) {
Juste renommer JailWizardByID en JailWizard

2019-07-29 21:25 UTC, rbobillo commented on first_iteration/magic/api/jail.go
> +	js, _ := json.Marshal(wz)
Rajouter quelques petits espaces histoire que le code respire ;)

2019-07-29 21:25 UTC, rbobillo commented on first_iteration/magic/api/die.go
> +func KillWizardByID(w *http.ResponseWriter, r *http.Request, db *sql.DB) (err error) {
Renommer KillWizardByID en KillWizard :)

2019-07-29 21:25 UTC, rbobillo commented on first_iteration/magic/magicinventory/magicinventory.go
> +		return err
Tu peux par exemple renvoyer un ErrWizardNotFound, dans le cas echeant :)

2019-07-31 11:05 UTC, rbobillot requested changes

2019-07-31 11:05 UTC, rbobillo commented on first_iteration/magic/internal/errors.go
> +var ( ErrWizNotFound = fmt.Errorf("wizard not found")
Alors j'avais mis ce nom en exemple,
on va dire que `Wiz`, n'est pas le terme adequat
`Wizard` serait plus ideal

Sinon, pour l'indentation, ca me gene un poil
-> n'oublie pas de repasser un `go fmt` pour tout le projet

2019-07-31 11:52 UTC, rbobillot requested changes

2019-07-31 11:52 UTC, rbobillo commented on first_iteration/magic/api/die.go
> +	(*w).WriteHeader(http.StatusOK)
Par defaut, le Header est en `StatusOK`, donc pas besoin de le re-ecrire dans le header
C'est d'ailleurs dit au runtime, au moment de la requete
```go
http: superfluous response.WriteHeader call from ...
```

2019-07-31 11:52 UTC, rbobillo commented on first_iteration/magic/api/jail.go
> +	(*w).WriteHeader(http.StatusOK)
Par defaut, le Header est en `StatusOK`, donc pas besoin de le re-ecrire dans le header
C'est d'ailleurs dit au runtime, au moment de la requete
```go
http: superfluous response.WriteHeader call from ...
```

2019-07-31 11:52 UTC, rbobillo commented on first_iteration/magic/api/wizards.go
> +	(*w).WriteHeader(http.StatusOK)
Par defaut, le Header est en `StatusOK`, donc pas besoin de le re-ecrire dans le header
C'est d'ailleurs dit au runtime, au moment de la requete
```go
http: superfluous response.WriteHeader call from ...
```

2019-07-31 11:52 UTC, rbobillo commented on first_iteration/magic/api/wizards.go
> +	(*w).WriteHeader(http.StatusOK)
Par defaut, le Header est en `StatusOK`, donc pas besoin de le re-ecrire dans le header
C'est d'ailleurs dit au runtime, au moment de la requete
```go
http: superfluous response.WriteHeader call from ...
```

2019-07-31 15:29 UTC, rbobillot requested changes

2019-07-31 15:29 UTC, rbobillo commented on first_iteration/magic/api/jail.go
> +
Ligne vide: il manque la gestion du code d'erreur http ?

2019-07-31 15:29 UTC, rbobillo commented on first_iteration/magic/api/jail.go
> +
Le dernier cas d'erreur n'est pas gere. Un truc du genre:
```go
	if err != nil {
		(*w).WriteHeader(http.StatusUnprocessableEntity)
		return err
	}
```

2019-07-31 15:29 UTC, rbobillo commented on first_iteration/magic/api/die.go
> +
Le dernier cas d'erreur n'est pas gere. Un truc du genre:
```go
	if err != nil {
		(*w).WriteHeader(http.StatusUnprocessableEntity)
		return err
	}
```

2019-07-31 15:29 UTC, rbobillo commented on first_iteration/magic/api/wizards.go
> +
Le dernier cas d'erreur n'est pas gere. Un truc du genre:
```go
	if err != nil {
		(*w).WriteHeader(http.StatusUnprocessableEntity)
		return err
	}
```

2019-07-31 15:29 UTC, rbobillo commented on first_iteration/magic/magicinventory/magicinventory.go
> +func GetWizardsByID(db *sql.DB, query string, args interface{}) (wz dao.Wizard, err error) {
Je viens de tilter, mais etant donne que la requete ne fait qu'un simple `SELECT`, et qu'elle ne filtre que par `ID`,
pas besoin de passer une interface en parametre, autant passer directement un id (qui, grace a mux, est une simple string):

```go
func GetWizardsByID(db *sql.DB, query string, id string) (wz dao.Wizard, err error)
```

2019-07-31 15:29 UTC, rbobillo commented on first_iteration/magic/magicinventory/magicinventory.go
> +            id         uuid        not null primary key,
Alors, c'est peut-etre moi qui ai fait ca,
mais attention a l'indentation (met des tabs plutot que des espaces, ca fait des decalages tout moches dans github ^^)

2019-07-31 15:39 UTC, rbobillot requested changes

2019-07-31 15:39 UTC, rbobillo commented on first_iteration/magic/api/wizards.go
> +
peut-etre gerer autrement les precedentes lignes:
```go
	wz, err := magicinventory.GetWizardsByID(db, query, id)

	if err != nil {
		(*w).WriteHeader(http.StatusNotFound)
		return err
	}

	js, err := json.Marshal(wz)

	if err != nil {
		(*w).WriteHeader(http.StatusUnprocessableEntity)
		return err
	}
```

2019-07-31 15:43 UTC, rbobillot requested changes

2019-07-31 15:43 UTC, rbobillo commented on first_iteration/magic/api/age.go
> +	//(*w).WriteHeader(http.StatusNoContent)
Ne pas commenter, il est essenciel que cette action se passe haha

2019-07-31 15:53 UTC, rbobillot requested changes

2019-07-31 15:53 UTC, rbobillo commented on first_iteration/magic/magicinventory/magicinventory.go
> +func DeleteWizardsByID(db *sql.DB, args interface{}) (err error) {
Meme remarque que pour `GetWizardsByID`

2019-07-31 16:05 UTC, rbobillot requested changes

2019-07-31 16:05 UTC, rbobillot commented on first_iteration/magic/api/spawn.go
> +	log.Println("new wizard created")
Attention, log inutile ;)

2019-07-31 16:05 UTC, rbobillo commented on first_iteration/magic/api/spawn.go
> +	(*w).WriteHeader(http.StatusCreated)
Alors, ca output un log "superfluous"
Ca ne devrait pas, mais je ne comprends pas pourquoi. Tu fais la bonne instruction en tout cas.

A la limite, commente cette ligne en disant que tout va bien:
```go
 	// outputs an irrelevant log: `http: superfluous response.WriteHeader call`
 	(*w).WriteHeader(http.StatusCreated)
```

2019-07-31 16:32 UTC, rbobillot requested changes

2019-07-31 16:32 UTC, rbobillo commented on first_iteration/magic/api/swaggerui/swagger.yaml
> +  /wizards/age:
ca ne risque pas de fonctionner ;)
`   /wizards/{id}/age:`

2019-07-31 18:40 UTC, rbobillot requested changes
Voila,
y a un gros refacto
Je te laisse mettre a jour ton code (avec copy/paste du mien, et ajout de ce qui manque)

Verifie aussi tes messages d'erreur (quelques fautes d'anglais)

2019-07-31 18:40 UTC, rbobillot commented on first_iteration/magic/magicinventory/magicinventory.go
> +func UpdateWizardsByID(db *sql.DB, query string, args interface{}) (wz dao.Wizard, err error) {
la fonction est a refaire
 - les parametres ne refletent pas le nom de la fonction: ou est l'ID ?
 - pas la genericite prevue a l'origine
```go
func UpdateWizardsByID(db *sql.DB, id string, query string, args ...interface{}) (wz dao.Wizard, err error) {
	args = append([]interface{}{id}, args...) // prepend id to args

	row := db.QueryRow(query, args...)

	err = row.Scan(&wz.ID, &wz.FirstName, &wz.LastName, &wz.Age, &wz.Category, &wz.Arrested, &wz.Dead)

	if err == sql.ErrNoRows {
		return wz, internal.ErrWizardNotFound
	}

	if err != nil {
		log.Println("cannot update wizard status")
		return wz, err
	}

	log.Printf("wizard %s's status has been updated", id)

	return wz, err
}
```

2019-07-31 18:40 UTC, rbobillo commented on first_iteration/magic/api/die.go
> +func KillWizard(w *http.ResponseWriter, r *http.Request, db *sql.DB) (err error) {
Fonction a refaire (cf UpdateWizardByID)
```go
func KillWizard(w *http.ResponseWriter, r *http.Request, db *sql.DB) (err error) {
	id := mux.Vars(r)["id"]

	log.Printf("/wizards/%s/die", id)

	(*w).Header().Set("Content-Type", "application/json; charset=UTF-8")

	query := "UPDATE wizards SET dead = $2 WHERE id = $1 RETURNING *;"
	wz, err := magicinventory.UpdateWizardsByID(db, id, query, true)

	if err == sql.ErrNoRows {
		(*w).WriteHeader(http.StatusNotFound)
		log.Println(fmt.Sprintf("wizard %s doesn't exists", id))
		return err
	}

	if err != nil {
		(*w).WriteHeader(http.StatusUnprocessableEntity)
		log.Printf("error: cannot kill wizard %s", id)
		return err
	}
	
	js, err := json.Marshal(wz)
	
	// TODO: handle error
	
	_, err = fmt.Fprintf(*w, string(js))

	// TODO: handle error
	
	return nil
}
```

2019-07-31 18:40 UTC, rbobillo commented on first_iteration/magic/magicinventory/magicinventory.go
> +func UpdateWizards(db *sql.DB, status string, value float64) (err error) {
Fonction a refaire:

```go
func UpdateWizards(db *sql.DB, query string, args ...interface{}) (err error) {
	_, err = db.Exec(query, args...)

	if err != nil {
		log.Printf("cannot update wizards")
		return err
	}

	log.Println(fmt.Sprintf("wizards updated"))

	return nil
}
```

2019-07-31 18:40 UTC, rbobillo commented on first_iteration/magic/api/age.go
> +func AgeWizards(w *http.ResponseWriter, r *http.Request, db *sql.DB) (err error) {
Fonction a refaire (cf UpdateWizards)

```go
func AgeWizards(w *http.ResponseWriter, r *http.Request, db *sql.DB) (err error) {
	var wizard dao.Wizard

	log.Println("/wizards/age")
	(*w).Header().Set("Content-Type", "application/json; charset=UTF-8")

	decoder := json.NewDecoder(r.Body)
	err = decoder.Decode(&wizard)

	if err != nil {
		(*w).WriteHeader(http.StatusMethodNotAllowed)
		log.Println("warning: cannot convert Body to JSON")
		return err
	}

	query := "UPDATE wizards SET age = age + $1;"
	err = magicinventory.UpdateWizards(db, query, wizard.Age)

	if err != nil {
		(*w).WriteHeader(http.StatusUnprocessableEntity)
		log.Println("error: cannot update wizards's age")
		return err
	}

	(*w).WriteHeader(http.StatusNoContent)
	log.Println("wizards age successfully updated")

	return nil
}
```

2019-07-31 18:40 UTC, rbobillo commented on first_iteration/magic/api/spawn.go
> +	(*w).WriteHeader(http.StatusCreated)
Erratum, j'ai compris:
selon les normes http,
si tu renvoies une 201, il ne faut pas renvoyer de data dans le body, c'est superfluous

2019-07-31 19:53 UTC, artemys commented on first_iteration/magic/api/swaggerui/swagger.yaml
> +  /wizards/age:
Alors, la je ne vois pas pourquoi ? La route Age ne s'applique pas a tout les wizards ?
Dans ce cas toute route Age es fausse

2019-07-31 23:04 UTC, artemys commented on first_iteration/magic/magicinventory/magicinventory.go
> +func UpdateWizardsByID(db *sql.DB, query string, args interface{}) (wz dao.Wizard, err error) {
Ici, je n'arrive pas a recuperer le parametre ID dans l'interface. lorsque je print 
[]interface{}{id} et args... je n'arrive que a afficher la variable query.
Ou ce trouve l'ID ??

2019-07-31 23:15 UTC, artemys commented on first_iteration/magic/magicinventory/magicinventory.go
> +func UpdateWizardsByID(db *sql.DB, query string, args interface{}) (wz dao.Wizard, err error) {
J'avais confondu l'ordre des arguments, mais la, peut tu me reexpliquer l'utilitee de l'interface, doit-je y stocker l'id et la query ?

2019-07-31 23:38 UTC, artemys commented on first_iteration/magic/api/die.go
> +func KillWizard(w *http.ResponseWriter, r *http.Request, db *sql.DB) (err error) {
JailWizard es tres similaire a KillWizard, es-ce que j'applique les meme modification a Jail ?

2019-08-01 10:08 UTC, rbobillot requested changes

2019-08-01 10:08 UTC, rbobillo commented on first_iteration/magic/api/swaggerui/swagger.yaml
> +      - "Age"
restons en minuscules, comme sur le reste du code: "age"

2019-08-01 14:30 UTC, rbobillot requested changes

2019-08-01 14:30 UTC, rbobillot commented on first_iteration/magic/api/die.go
> +		log.Println(fmt.Sprintf("wizard %s is already dead or doesn't exists", id))
Alors j'en ai vu passer pas mal dans le code: `log.Println(fmt.Sprintf(...))`
simplifie toi la vie, et soulage ton compilo: `log.Printf(...)`

2019-08-01 14:30 UTC, rbobillo commented on first_iteration/magic/api/die.go
> +		log.Println(fmt.Sprintf("wizard %s is already dead or doesn't exists", id))
Du coup j'ai reflechi.
Le probleme dans nos code, c'est que nos logs ne sont pas relevant, car sans contexte semantique.

Ma premiere solution aurait ete d'utiliser un une lib de logging (https://github.com/sirupsen/logrus)

Mais on va rester un poil plus simple:
dans `internal/`, cree un fichier `logging.go`, tel que:

```go
package internal

import "log"

type Log string

func (msg Log) Debug() {
	log.SetPrefix("\033[0mDEBUG\033[0m ")
	log.SetFlags(log.Ldate | log.Ltime | log.Lshortfile)

	log.Println(msg)
}

func (msg Log) Error() {
	log.SetPrefix("\033[91mERROR\033[0m ")
	log.SetFlags(log.Ldate | log.Ltime | log.Lshortfile)

	log.Println(msg)
}

func (msg Log) Info() {
	log.SetPrefix("\033[95mINFO\033[0m  ")
	log.SetFlags(log.Ldate | log.Ltime | log.Lshortfile)

	log.Println(msg)
}

func (msg Log) Warn() {
	log.SetPrefix("\033[93mWARN\033[0m  ")
	log.SetFlags(log.Ldate | log.Ltime | log.Lshortfile)

	log.Println(msg)
}
```

ainsi, tu pourra appeler tout ca dans tes autres fichiers:
```go
	internal.Log(fmt.Sprintf("/wizards/%s", id)).Debug()
	internal.Log(fmt.Sprintf("/wizards/%s", id)).Error()
	internal.Log(fmt.Sprintf("/wizards/%s", id)).Info()
	internal.Log(fmt.Sprintf("/wizards/%s", id)).Warn()
```

2019-08-04 20:04 UTC, rbobillot requested changes

2019-08-04 20:04 UTC, rbobillot commented on first_iteration/magic/internal/logging.go
> +package internal
Je propose un gros refacto

```go
package internal

import (
	"log"
)

const (
	debugLvl = "\033[0mDEBUG\033[0m "
	errorLvl = "\033[91mERROR\033[0m "
	infoLvl  = "\033[95mINFO\033[0m  "
	warnLvl  = "\033[93mWARN\033[0m  "
)

func stdOutLog(level string, message string) {
	log.SetPrefix(level)
	log.SetFlags(log.Ldate | log.Ltime | log.Lshortfile)

	_ = log.Output(3, message) // calldepth = 3, so we can find the original calling function/file
}

// Debug set debugs attributes
// to a message then
// print i
func Debug(msg string) {
	stdOutLog(debugLvl, msg)
}

// Error set errors attributes
// to a message then
// print it
func Error(msg string) {
	stdOutLog(errorLvl, msg)
}

// Info set infos attributes
// to a message then
// print it
func Info(msg string) {
	stdOutLog(infoLvl, msg)
}

// Warn set Warnings attributes
// to a message then
// print it
func Warn(msg string) {
	stdOutLog(warnLvl, msg)
}
```

2019-08-04 20:04 UTC, rbobillot commented on first_iteration/magic/main.go
> +		panic(err)
remplacer `panic` par un log error

2019-08-04 20:04 UTC, rbobillot commented on first_iteration/magic/magicinventory/magicinventory.go
> +		internal.Log(fmt.Sprintf("cannot create wizard: %+v , %s ", w, err )).Error()
logLevel: Warn

pour le format de Wizard, un simple `%v` suffit

2019-08-04 20:04 UTC, rbobillot commented on first_iteration/magic/magicinventory/magicinventory.go
> +	internal.Log(fmt.Sprintf("created wizard: %+v", w)).Debug()
pour le format de Wizard, un simple `%v` suffit

2019-08-04 20:04 UTC, rbobillot commented on first_iteration/magic/magicinventory/magicinventory.go
> +		internal.Log(fmt.Sprintf("cannot delete wizard %s", id)).Error()
logLevel: Warn

2019-08-04 20:04 UTC, rbobillot commented on first_iteration/magic/magicinventory/magicinventory.go
> +	internal.Log(fmt.Sprintf("wizards %s have been deleted", id)).Debug()
verifie bien tes messages de log (-> `has been deleted`)

2019-08-04 20:04 UTC, rbobillot commented on first_iteration/magic/magicinventory/magicinventory.go
> +		internal.Log(fmt.Sprintf("cannot get all wizards")).Error()
logLevel: Warn

2019-08-04 20:04 UTC, rbobillot commented on first_iteration/magic/magicinventory/magicinventory.go
> +			internal.Log(fmt.Sprintf("cannot get all wizards: error while browsing wizards")).Error()
loglevel: Warn

2019-08-04 20:04 UTC, rbobillot commented on first_iteration/magic/magicinventory/magicinventory.go
> +		internal.Log(fmt.Sprintf("cannot get wizards %s", id)).Error()
logLevel: Warn

2019-08-04 20:04 UTC, rbobillot commented on first_iteration/magic/magicinventory/magicinventory.go
> +	internal.Log(fmt.Sprintf("wizard %s have been found", id)).Debug()
attention au message (-> `has been`)

2019-08-04 20:04 UTC, rbobillot commented on first_iteration/magic/magicinventory/magicinventory.go
> +		internal.Log(fmt.Sprintf("error while opening db connection")).Error()
loglevel: Warn

2019-08-04 20:04 UTC, rbobillot commented on first_iteration/magic/magicinventory/magicinventory.go
> +		panic(err)
remplacer panic par un log error

2019-08-04 20:04 UTC, rbobillot commented on first_iteration/magic/magicinventory/magicinventory.go
> +		internal.Log(fmt.Sprintf("cannot update wizards")).Error()
loglevel: Warn

2019-08-04 20:04 UTC, rbobillot commented on first_iteration/magic/magicinventory/magicinventory.go
> +		internal.Log(fmt.Sprintf("cannot update wizard status")).Error()
loglevel: Warn

2019-08-04 20:04 UTC, rbobillot commented on first_iteration/magic/magicinventory/magicinventory.go
> +			internal.Log(fmt.Sprintf("cannot populate magic inventory")).Error()
loglevel: Warn

2019-08-04 20:04 UTC, rbobillot commented on first_iteration/magic/api/wizards.go
> +		internal.Log(fmt.Sprintf("wizard %s may not exist", id)).Error()
loglevel: Warn

2019-08-04 20:04 UTC, rbobillot commented on first_iteration/magic/api/wizards.go
> +		internal.Log(fmt.Sprintf("cannot find wizard %s", id)).Error()
loglevel: Warn

pourquoi ne pas ajouter l'erreur au log:
```go
internal.Log(fmt.Sprintf("cannot find wizard %s (%s)", id, err)).Warn()
```
qqch dans le genre

2019-08-04 20:04 UTC, rbobillot commented on first_iteration/magic/api/wizards.go
> +		internal.Log(fmt.Sprintf("wizards doesn't exists")).Error()
loglevel: Warn

2019-08-04 20:04 UTC, rbobillot commented on first_iteration/magic/api/wizards.go
> +		internal.Log(fmt.Sprintf("cannot find all wizards")).Error()
loglevel: Warn

2019-08-04 20:04 UTC, rbobillot commented on first_iteration/magic/api/wizards.go
> +		internal.Log(fmt.Sprintf("cannot serialize Wizard to JSON")).Error()
loglevel: Warn

2019-08-04 20:04 UTC, rbobillot commented on first_iteration/magic/api/spawn.go
> +		internal.Log(fmt.Sprintf("cannot serialize Wizard to JSON")).Error()
Le debat est ouvert (ca vaut pour les autres fichiers)
Ici, le loglevel en Error me va tres bien. Je l'aurai mis en Warn, mais en reflechissant, Error a totalement du sens.

De maniere generale, le loglevel Error peut avoir 2 significations:
 - une erreur, d'un point de vue metier (mais genre une erreur relativement grave)
 - un incident "fatal" dans le code: quelque chose qui entrave le bon fonctionnement du programme (qui pourrait eventuellement necessiter un redemarrage du programme)

2019-08-04 20:04 UTC, rbobillot commented on first_iteration/magic/api/obliviate.go
> +		internal.Log(fmt.Sprintf("cannot obliviate wizards %s", id)).Error()
loglevel: Warn

2019-08-04 20:04 UTC, rbobillot commented on first_iteration/magic/api/jail.go
> +		internal.Log(fmt.Sprintf("wizard %s doesn't exists", id)).Error()
loglevel: Warn

2019-08-04 20:04 UTC, rbobillot commented on first_iteration/magic/api/jail.go
> +		internal.Log(fmt.Sprintf("cannot arrest wizard %s", id)).Error()
loglevel: Warn

2019-08-04 20:04 UTC, rbobillot commented on first_iteration/magic/api/die.go
> +		internal.Log(fmt.Sprintf("wizard %s doesn't exists")).Error()
loglevel: Warn

2019-08-04 20:04 UTC, rbobillot commented on first_iteration/magic/api/die.go
> +		internal.Log(fmt.Sprintf("cannot kill wizard %s")).Error()
loglevel: Warn

2019-08-04 20:04 UTC, rbobillot commented on first_iteration/magic/api/age.go
> +		internal.Log(fmt.Sprintf("cannot update wizards's age")).Error()
loglevel: Warn

2019-08-04 20:04 UTC, rbobillot commented on first_iteration/magic/api/age.go
> +	internal.Log(fmt.Sprintf("wizards age successfully updated")).Debug()
loglevel: Info

On est sur du log qui peut apporter de la valeur metier.
On peut donc se permettre de le passer en `Info`, et de mettre des messages de log, aussi pertinents que possible, du genre:
```go
internal.Log(fmt.Sprintf("every wizards got older (+%f years)", wizard.Age)).Info()
```

2019-08-04 20:04 UTC, rbobillot commented on first_iteration/magic/api/die.go
> +	internal.Log(fmt.Sprintf("wizard %s dead", id)).Debug()
loglevel: Info

2019-08-04 20:04 UTC, rbobillot commented on first_iteration/magic/api/jail.go
> +	internal.Log(fmt.Sprintf("wizard %s id in jail", id)).Debug()
loglevel: Info

On est sur du log qui peut apporter de la valeur metier.
On peut donc se permettre de le passer en `Info`, et de mettre des messages de log, aussi pertinents que possible, du genre:
```go
internal.Log(fmt.Sprintf("wizard %s has been sent to jail", id)).Info()
```

2019-08-04 20:04 UTC, rbobillot commented on first_iteration/magic/api/obliviate.go
> +	internal.Log(fmt.Sprintf("wizard %s have been oblivited", id)).Debug()
loglevel: Info

On est sur du log qui peut apporter de la valeur metier.
On peut donc se permettre de le passer en Info, et de mettre des messages de log, aussi pertinents que possible, du genre:
```go
internal.Log(fmt.Sprintf("wizard %s has been oblivited", id)).Info()
```

2019-08-04 20:04 UTC, rbobillot commented on first_iteration/magic/api/spawn.go
> +	internal.Log(fmt.Sprintf("new wizard created")).Debug()
loglevel: Info

On est sur du log qui peut apporter de la valeur metier.
On peut donc se permettre de le passer en `Info`, et de mettre des messages de log, aussi pertinents que possible, du genre:
```go
internal.Log(fmt.Sprintf("wizard has spawned: %v", wizard)).Info()
```

2019-08-04 21:08 UTC, artemys commented on first_iteration/magic/main.go
> +		panic(err)
Le probleme ici c'est que la log error() prend une string et err es de type error.

2019-08-05 00:30 UTC, rbobillot approved these changes
Il y aura sans doute des remaniements a l'avenir,
mais pour moi, tout est bon

2019-08-05 00:36 UTC, merged